folders:
- name: catcodec-releases
- name: grfcodec-releases
- name: nforenum-releases
- name: nosound-releases
- name: opengfx-releases
- name: openmsx-releases
- name: opensfx-releases
- name: openttd-releases
- name: openttd-useful-releases
- name: osie-releases

- name: discord-social-releases
- name: gog-galaxy-social-releases
- name: steam-social-releases

- name: openttd-nightlies
  subfolders: per-year
  override-name: in-folder-name
  sort: normal
  cleanup-after: 3mo
  cleanup-keep: source

- name: openttd-branches
  subfolders: per-name
  override-name: in-folder-name
  sort: normal
  cleanup-after: 1mo
  cleanup-keep: 1

- name: grfcodec-nightlies
  override-name: nightly
  sort: normal

- name: opengfx-nightlies
  override-name: in-folder-name
  sort: normal
  cleanup-after: 3mo
  cleanup-keep: 3

- name: opensfx-nightlies
  override-name: in-folder-name
  sort: normal
  cleanup-after: 3mo
  cleanup-keep: 3

- name: openmsx-nightlies
  override-name: in-folder-name
  sort: normal
  cleanup-after: 3mo
  cleanup-keep: 3
