name: Testing

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

concurrency:
  group: testing-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  flake8:
    name: Flake8
    uses: OpenTTD/actions/.github/workflows/rw-py-flake8.yml@v4
    with:
      python-path: cdn/cdn_generator

  black:
    name: Black
    uses: OpenTTD/actions/.github/workflows/rw-py-black.yml@v4
    with:
      python-path: cdn/cdn_generator
      python-version: 3.8

  annotation_check:
    name: Annotation Check
    needs:
    - flake8
    - black

    uses: OpenTTD/actions/.github/workflows/rw-annotation-check.yml@v4
