name: Testing

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

concurrency:
  group: testing-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  flake8:
    name: Flake8
    uses: OpenTTD/actions/.github/workflows/rw-py-flake8.yml@v5
    with:
      python-path: cdn/cdn_generator

  black:
    name: Black
    uses: OpenTTD/actions/.github/workflows/rw-py-black.yml@v5
    with:
      python-path: cdn/cdn_generator
      python-version: 3.8

  install:
    name: Install

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -r cdn/requirements.txt

  annotation_check:
    name: Annotation Check
    needs:
    - flake8
    - black

    uses: OpenTTD/actions/.github/workflows/rw-annotation-check.yml@v5
