name: Testing

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  flake8:
    name: Flake8
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Flake8
      uses: TrueBrain/actions-flake8@v2
      with:
        path: cdn/cdn_generator

  black:
    name: Black
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Black
      run: |
        python -m pip install --upgrade pip
        pip install black
        black -l 120 --check cdn/cdn_generator

  check_annotations:
    name: Check Annotations
    needs:
    - flake8
    - black
    # not codeql, as that reports its own status

    if: always() && github.event_name == 'pull_request'

    runs-on: ubuntu-latest

    steps:
    - name: Check annotations
      uses: OpenTTD/actions/annotation-check@v2
